#pragma once

#include "bpe/tokenizer.h"
#include <filesystem>
#include <fstream>
#include <string>
#include <nlohmann/json.hpp>

namespace test_helpers {

// Path to test data directory (set via CMake compile definition).
inline std::filesystem::path data_dir() {
    return TEST_DATA_DIR;
}

inline std::filesystem::path fixtures_dir() {
    return FIXTURES_DIR;
}

// Simple corpus for quick tests.
inline std::string tiny_corpus() {
    return "the cat sat on the mat. the cat ate the rat. "
           "the dog sat on the log. the dog ate the frog.";
}

// Medium corpus — repeated text for benchmarking training speed.
inline std::string medium_corpus(size_t repeat = 100) {
    std::string base =
        "In a small village, there lived a young girl named Lily. She loved to explore "
        "the forest near her home. One day, she found a shiny stone by the river. "
        "The stone glowed with a warm light. Lily picked it up and felt happy. "
        "She showed it to her friend Tom. Tom said it was a magic stone. "
        "They decided to go on an adventure together. They walked through the tall trees "
        "and crossed the old bridge. On the other side, they found a beautiful garden. "
        "The garden had flowers of every color. Lily and Tom played there until sunset. "
        "When they went home, Lily put the stone on her shelf. It still glowed softly. "
        "She smiled and went to sleep, dreaming of their next adventure.\n";
    std::string result;
    result.reserve(base.size() * repeat);
    for (size_t i = 0; i < repeat; ++i) {
        result += base;
    }
    return result;
}

// Large corpus — for performance testing (about 1MB).
inline std::string large_corpus() {
    return medium_corpus(2000);
}

// Train a tokenizer on the tiny corpus with a small vocab.
inline bpe::Tokenizer train_tiny(uint32_t vocab_size = 280) {
    bpe::Tokenizer tok;
    tok.train(tiny_corpus(), vocab_size);
    return tok;
}

// Train a tokenizer with special tokens.
inline bpe::Tokenizer train_with_specials(uint32_t vocab_size = 280) {
    bpe::Tokenizer tok;
    tok.train(tiny_corpus(), vocab_size, {"<|endoftext|>", "<|pad|>"});
    return tok;
}

// Load reference data from JSON fixtures (generated by scripts/gen_fixtures.py).
inline nlohmann::json load_fixture(const std::string& name) {
    auto path = fixtures_dir() / name;
    std::ifstream f(path);
    if (!f) {
        throw std::runtime_error("Fixture not found: " + path.string() +
                                 "\nRun: python3 scripts/gen_fixtures.py");
    }
    return nlohmann::json::parse(f);
}

// Temporary directory for save/load tests.
inline std::filesystem::path temp_dir() {
    auto p = std::filesystem::temp_directory_path() / "bpe_test_tmp";
    std::filesystem::create_directories(p);
    return p;
}

inline void cleanup_temp_dir() {
    auto p = std::filesystem::temp_directory_path() / "bpe_test_tmp";
    std::filesystem::remove_all(p);
}

} // namespace test_helpers
