#include <gtest/gtest.h>
#include "bpe/tokenizer.h"
#include "test_helpers.h"

#include <nlohmann/json.hpp>
#include <filesystem>

using namespace bpe;
using json = nlohmann::json;

// ═══════════════════════════════════════════════════════════════════
// Correctness comparison against reference implementations.
//
// These tests load expected outputs generated by scripts/gen_fixtures.py
// which runs tiktoken (GPT-2) and HuggingFace tokenizers on test inputs.
//
// Run `python3 scripts/gen_fixtures.py` to generate the fixture files
// before running these tests.
// ═══════════════════════════════════════════════════════════════════

class CorrectnessTest : public ::testing::Test {
protected:
    void SetUp() override {
        auto fixture_path = test_helpers::fixtures_dir() / "reference_encodings.json";
        if (!std::filesystem::exists(fixture_path)) {
            GTEST_SKIP() << "Reference fixtures not found. "
                         << "Run: python3 scripts/gen_fixtures.py";
        }
        fixtures_ = test_helpers::load_fixture("reference_encodings.json");
    }
    json fixtures_;
};

// Test that our tokenizer, when loaded with GPT-2 vocab/merges,
// produces the same token IDs as tiktoken for various inputs.
TEST_F(CorrectnessTest, MatchesTiktokenGPT2) {
    // Load GPT-2 vocab and merges (generated by gen_fixtures.py).
    auto gpt2_dir = test_helpers::fixtures_dir() / "gpt2";
    if (!std::filesystem::exists(gpt2_dir / "vocab.json")) {
        GTEST_SKIP() << "GPT-2 fixtures not found. "
                     << "Run: python3 scripts/gen_fixtures.py";
    }

    auto tok = Tokenizer::load(gpt2_dir);

    for (auto& [text, expected_ids_json] : fixtures_["tiktoken_gpt2"].items()) {
        std::vector<uint32_t> expected;
        for (auto& id : expected_ids_json) {
            expected.push_back(id.get<uint32_t>());
        }
        auto actual = tok.encode(text);
        EXPECT_EQ(actual, expected)
            << "Mismatch for text: \"" << text << "\""
            << "\n  Expected " << expected.size() << " tokens"
            << "\n  Got " << actual.size() << " tokens";
    }
}

// Test that decode(tiktoken_ids) produces the original text.
TEST_F(CorrectnessTest, DecodeTiktokenIds) {
    auto gpt2_dir = test_helpers::fixtures_dir() / "gpt2";
    if (!std::filesystem::exists(gpt2_dir / "vocab.json")) {
        GTEST_SKIP() << "GPT-2 fixtures not found.";
    }

    auto tok = Tokenizer::load(gpt2_dir);

    for (auto& [text, expected_ids_json] : fixtures_["tiktoken_gpt2"].items()) {
        std::vector<uint32_t> ids;
        for (auto& id : expected_ids_json) {
            ids.push_back(id.get<uint32_t>());
        }
        auto decoded = tok.decode(ids);
        EXPECT_EQ(decoded, text)
            << "Decode mismatch for text: \"" << text << "\"";
    }
}

// ═══════════════════════════════════════════════════════════════════
// Training correctness: our merges should match the CS336 reference.
// ═══════════════════════════════════════════════════════════════════

TEST_F(CorrectnessTest, TrainingMergesMatchReference) {
    if (!fixtures_.contains("training_reference")) {
        GTEST_SKIP() << "Training reference not in fixtures.";
    }

    auto& ref = fixtures_["training_reference"];
    std::string corpus = ref["corpus"].get<std::string>();
    uint32_t vocab_size = ref["vocab_size"].get<uint32_t>();

    Tokenizer tok;
    tok.train(corpus, vocab_size);

    // Compare merge sequence.
    auto& expected_merges = ref["merges"];
    auto& actual_merges = tok.merges();

    ASSERT_EQ(actual_merges.size(), expected_merges.size())
        << "Different number of merges";

    for (size_t i = 0; i < actual_merges.size(); ++i) {
        auto& em = expected_merges[i];
        EXPECT_EQ(actual_merges[i].left, em["left"].get<uint32_t>())
            << "Merge " << i << " left mismatch";
        EXPECT_EQ(actual_merges[i].right, em["right"].get<uint32_t>())
            << "Merge " << i << " right mismatch";
        EXPECT_EQ(actual_merges[i].merged, em["merged"].get<uint32_t>())
            << "Merge " << i << " merged ID mismatch";
    }
}

// ═══════════════════════════════════════════════════════════════════
// Compression ratio comparison.
// ═══════════════════════════════════════════════════════════════════

TEST_F(CorrectnessTest, CompressionRatioReasonable) {
    // Train on medium corpus and check compression ratio.
    Tokenizer tok;
    auto corpus = test_helpers::medium_corpus(50);
    tok.train(corpus, 500);

    auto ids = tok.encode(corpus);
    double ratio = static_cast<double>(corpus.size()) / ids.size();

    // BPE with 244 merges on English text should compress at least 2x.
    EXPECT_GT(ratio, 2.0)
        << "Compression ratio too low: " << ratio
        << " (expected > 2.0 for vocab_size=500)";

    // Sanity: shouldn't be absurdly high either.
    EXPECT_LT(ratio, 50.0)
        << "Compression ratio suspiciously high: " << ratio;
}

// ═══════════════════════════════════════════════════════════════════
// Token count comparison against tiktoken.
// ═══════════════════════════════════════════════════════════════════

TEST_F(CorrectnessTest, TokenCountMatchesTiktoken) {
    auto gpt2_dir = test_helpers::fixtures_dir() / "gpt2";
    if (!std::filesystem::exists(gpt2_dir / "vocab.json")) {
        GTEST_SKIP() << "GPT-2 fixtures not found.";
    }

    auto tok = Tokenizer::load(gpt2_dir);

    if (!fixtures_.contains("tiktoken_counts")) {
        GTEST_SKIP() << "Token count fixtures not found.";
    }

    for (auto& [text, expected_count_json] : fixtures_["tiktoken_counts"].items()) {
        auto expected_count = expected_count_json.get<size_t>();
        auto actual_count = tok.encode(text).size();
        EXPECT_EQ(actual_count, expected_count)
            << "Token count mismatch for: \"" << text << "\"";
    }
}
